### ISSUE TITLE
Endre kodelisten som brukes for forslag til distribusjonsformater

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/dataset-catalog-gui-old#28]
Nå brukes media types fra IANA, det skal endres til det kontrollerte vokabular file-type fra EUs Publications Office

fra reference-data finnes disse på endepunktene `/iana/media-types` og `/eu/file-types`

**Comment by NilsOveTen** [comment]
Før dette kan startes på trenger vi forslag til nye versjoner av div tekster, ref "Format" i registrering:

![Screenshot from 2023-03-10 14-45-47](https://user-images.githubusercontent.com/50194012/224331919-dd7ad48a-4ae0-4c6c-9dbc-56ba2e00071e.png)

**Comment by KurtStian** [comment]
Forslag til ny hjelpetekst:

Format (datasett)

Anbefalt
Velg format(er) for distribusjonen. 

Færre anbefalinger
Listen kommer fra EU publication office sin liste over offisielle filtyper: [File type](http://publications.europa.eu/resource/authority/file-type) Se spesifikasjonen [Distribusjon:format](https://data.norge.no/specification/dcat-ap-no#Distribusjon-format)


Tekst søkfelt: «Søk på og velg blant registrerte filtyper»
