### ISSUE TITLE
Bug: "Legg til relaterte datasett" funker ikke

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/dataset-catalog-gui-old#37]
Funksjonen "Legg til relaterte datasett" funker ikke. Datasettene (og serier!) ligger som autoforslag men får ikke opprettet relasjon.

[Nevnt i denne brukerhistorien](https://github.com/Informasjonsforvaltning/behov/issues/722#issuecomment-1570126014)

**Comment by terjesyl** [comment]
@hegeaal vet du noe om denne? Anslag på hvor mye tid det tar å fikse?

**Comment by oystein-asnes** [comment]
Obs. Fikk instruks om å legge disse inn i fdk-portal-repoet,så her er et duplikat, @terjesyl : https://github.com/Informasjonsforvaltning/fdk-portal/issues/1706

**Comment by terjesyl** [comment]
duplikat av https://github.com/Informasjonsforvaltning/dataset-catalog-gui-old/issues/38
