### ISSUE TITLE
Erstatte fulltext-search med search-service

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/dataset-catalog-gui-old#62]
Søk på datasett, dataservice, begrep og informasjonsmodeller via search-service

**Comment by KurtStian** [comment]
[Test av søk i registreringsløsning.docx](https://github.com/Informasjonsforvaltning/dataset-catalog-gui-old/files/14693417/Test.av.sok.i.registreringslosning.docx)
